spring:
  docker:
    compose:
      enabled: false

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

api:
  security:
    token:
      secret: integration-test-secret-not-for-production
