server:
  port: 8080
spring:
  application:
    name: finance-manager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always