package com.amorim.finance_manager.shared.exception;

public enum ApiErrorCode {

    VALIDATION_ERROR,
    INVALID_REQUEST,

    INVALID_CREDENTIALS,
    UNAUTHORIZED,

    ACCOUNT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    EMAIL_ALREADY_EXISTS,

    INVALID_PROFILE_UPDATE,
    INVALID_ACCOUNT_UPDATE,
    INACTIVE_ACCOUNT,
    CATEGORY_TYPE_MISMATCH,
    INVALID_CATEGORY_UPDATE,
    INVALID_BALANCE_AMOUNT,
    INVALID_TRANSACTION,
    INVALID_TRANSACTION_STATUS,
    INVALID_TRANSFER,

    OPTIMISTIC_LOCK_CONFLICT,

    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_SERVER_ERROR,

    TRANSACTION_ALREADY_CANCELLED,

    INVALID_REPORT_PERIOD
}
